config/routes.rb
Rails.application.routes.draw do
  
  get 'comments/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'staticpages#home'
  get  '/help',    to: 'staticpages#help' 
  get  '/about',   to: 'staticpages#about'
  get  '/contact', to: 'staticpages#contact'
  get  '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
  # memberだと、 users/:id/following, collectionだと users/following 
    member do
      # GET request, following action, following_user_path(:id)
      get :following, :followers
    end
  end
  # GET /account_activation/トークン/edit 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts do
    resource :favorites, only: [:show, :create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment_content, presence:true, length: { maximum: 500 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)  #コメント送信後は、一つ前のページへリダイレクトさせる。
    else
      redirect_back(fallback_location: root_path)  #同上
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      # 更新に成功した場合を扱う。
      flash[:success] = "Comment updated"
      redirect_to @post
    else
      flash[:danger] = "Comment failed"
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.find_by(post_id: @post.id)
    @comment.destroy
    redirect_to post_path(params[:post_id])
  end

  private
    def comment_params
     #params.require(:comment).permit(:comment_content, :post_id)  
      params.require(:comment).permit(:comment_content).merge(post_id: params[:post_id])
      #formにてpost_idパラメータを送信して、コメントへpost_idを格納するようにする必要がある。
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_edit.html.erb
<%# comment delete or edit %>
    <% if current_user?(c.user) %>
      <div class="link_to">
        <%= link_to "delete", post_comment_path(post, c), method: :delete, data: { confirm: "You sure?" } %>
          <!--comment => comment_path-->
      </div>
      <div class="link_to">
        <%= link_to "edit", edit_post_comment_path(post, c) %>
      </div>
    <%# login user が投稿者だった場合、削除のみ可能 %>
    <% elsif current_user.id == post.user_id %>
      <div class="link_to">
        <%= link_to "delete", post_comment_path(post, c), method: :delete, data: { confirm: "You sure?" } %>
          <!--comment => comment_path-->
      </div>
    <% end %>

app/views/comments/_comment_form.html.erb
<%= form_with(model:[@post, @comment]) do |f| %>
  <%= f.text_area :comment_content %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<% provide(:title, "Edit Comment") %>
<% provide(:button_text, '更新') %>

<p class="margin-top">コメントする</p>
<%= render 'comment_form' %>