config/routes.rb
Rails.application.routes.draw do
  
  get 'comments/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'staticpages#home'
  get  '/help',    to: 'staticpages#help' 
  get  '/about',   to: 'staticpages#about'
  get  '/contact', to: 'staticpages#contact'
  get  '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
  # memberだと、 users/:id/following, collectionだと users/following 
    member do
      # GET request, following action, following_user_path(:id)
      get :following, :followers
    end
  end
  # GET /account_activation/トークン/edit 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts do
    resource :favorites, only: [:show, :create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<!--staticpages/home.html.erb-->
<% if @feed_items.any? %>
  <ol class="posts">
    <!-- collectionを渡すと、<li>を列挙してくれる -->
    <!-- @feed_items do |feed_item| -->
      <!-- render feed_item -->
    <!-- end -->
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <!--object変数(key)に、参照しているオブジェクト(value)を渡す => パーシャルでobject変数を作成 -->
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :title, '投稿タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :content, '投稿文' %>
    <%= f.text_area :content %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/shared/_not_logged_form.html.erb
<h1>Welcome to the Sample App</h1>
  
<h2>
  This is the home page for the
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: false) do |f| %>
  <!--object変数(key)に、参照しているオブジェクト(value)を渡す => パーシャルでobject変数を作成 -->
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :title, '投稿タイトル' %>
    <%= f.text_field :title, class: 'form-control', autofocus: true %>
    <%= f.label :content, '投稿文' %>
    <%= f.text_area :content %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%=  @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<span><%= current_user.name %></span>
<div><%= link_to "view my profile", current_user %></div>
<span><%= pluralize(current_user.posts.count, "post") %></span>

app/views/shared/_user_small_info.html.erb
<%= link_to gravatar_for(c.user, size: 30), c.user %>
<span class="user">
  <%= c.user.name %>
</span>
<span class="timestamp">
  | Posted <%= time_ago_in_words(c.created_at) %> ago.
</span>

app/views/shared/_welcome_form.html.erb
<h1>Welcome to the Sample App</h1>
<h2>
  This is the home page for the
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>