config/routes.rb
Rails.application.routes.draw do
  
  get 'comments/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'staticpages#home'
  get  '/help',    to: 'staticpages#help' 
  get  '/about',   to: 'staticpages#about'
  get  '/contact', to: 'staticpages#contact'
  get  '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
  # memberだと、 users/:id/following, collectionだと users/following 
    member do
      # GET request, following action, following_user_path(:id)
      get :following, :followers
    end
  end
  # GET /account_activation/トークン/edit 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts do
    resource :favorites, only: [:show, :create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # => user_id <-> post_id
  # => Default: foreign_key: user_id  問題なし

  # favoritesメソッド: いいねをした人の
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  # => @post.favorites.map(&:user)

  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: :user
  # => @post.comments.map(&:user)

  default_scope -> { self.order(created_at: :desc) }    # order :順序
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 5000 }
  validates :title, presence: true, length: { maximum: 50 }

  # favorite Tableのuser.idに一致するレコードを検索し、それが存在すればtrue
  def favorited?(user)
    self.favorites.where(user_id: user.id).exists?
  end
 #exits いる？　likesampleでは下記で定義している
 # /Users/masatosawada/environment/like_sample/app/models/user.rb
#  def already_liked?(post)
#   self.likes.exists?(post_id: post.id)
#  end
# ↓
# user.rbに定義してみる


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user,   only: [:edit, :destroy]
  
  def index
    posts = Post.includes(:favorite_users).sort {|a,b| b.favorite_users.size <=> a.favorite_users.size}
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @favorite_users = @post.favorite_users
  end

  def new
    @post = current_user.posts.build
  end

  def create 
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'posts/new'
      # redirect_to root_url
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      # 更新に成功した場合を扱う。
      flash[:success] = "Post updated"
      redirect_to @post
    else
      render 'edit'
    end
  end

  
  # DELETE /posts/:id
  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    # 一個前のページに戻す(つまり画面を変えないで削除する)
    # redirect_back(fallback_location: root_url)
    # これでもOK=> redirect_to request.referrer || root_url
    redirect_to root_url
    # 一つ前のページは/posts/のため、
    # そこにGETリクエストを送っても、そんなパスはない
  end
  
  private

    # strong parameter
    def post_params
      self.params.require(:post).permit(:content, :title)
      # params[:post][:content, :title] 
      # => post のデータの集合を渡すんだけど、其の中のcontentとtitleのみに限定して渡しますよ
    end
    
    # current_userがdeleteしようとしている投稿を保有していないならrootへ飛ぶ
    def correct_user
          @post = current_user.posts.find_by(id: params[:id])
          redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>" >
    <%= link_to gravatar_for(post.user, size: 50), post.user %>
    <span class="user">
      <%= link_to post.user.name, post.user %>
    </span>
    <span class="post-title">
      <%= link_to post.title, post_url(post.id) %>
    </span>
    <span class="content">
      <%= truncate(post.content, length: 100) %>
      <%#= post.content.truncate(30) %>
      <% if post.content.size > 100 %>
        <%= link_to "続きを見る", post_url(post.id) %>
      <% end %>
    </span>
    <span>
      <i class="fa-solid fa-thumbs-up"></i>
      <%= post.favorites.count %>
    </span>
    <span>
      <i class="fa-solid fa-comment"></i>
      <%= post.comments.count %>
    </span>

    <!-- time_ago_in_words :何分前を表示するメソッド -->
    <span class="timestamp">
      Posted <%= time_ago_in_words(post.created_at) %> ago.
      <% if current_user?(post.user) %>
        <!--post => post_path-->
        <%= link_to "delete", post, method: :delete,
                                        data: { confirm: "You sure?" } %>
      <% end %>
    </span>
</li>

app/views/posts/_post_edit.html.erb
<% if current_user?(post.user) %>
<!--post => post_path-->
  <div class="link_to">
    <%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } %>
  </div>
  <%# 編集機能 %>
  <div class="link_to">
    <%= link_to "edit", edit_post_path(post) %>
  </div>
<% elsif current_user.id == post.user_id %>
  <div class="link_to">
    <%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit post") %>
<% provide(:button_text, '更新') %>
<div class="row">
    <section class="user_info"> <%= render 'shared/user_info' %> </section>
    <section class="post_form"> <%= render 'shared/post_form' %> </section> 
</div>

app/views/posts/index.html.erb
<% provide(:title, 'Favorite Post Ranking') %>
<h1>Favorite Post Ranking</h1>

<%= paginate @posts %>

<ul class="posts">
  <% @posts.each.with_index(1) do |post, i|%>
    第<%= i %>位
    <%= render partial: 'posts/post', locals: { post: post } %>
  <% end %>
</ul>

<%= paginate @posts %>

app/views/posts/new.html.erb
<% provide(:title, "Post form") %>
<% provide(:button_text, '投稿') %>
<div class="row">
    <section class="user_info"> <%= render 'shared/user_info' %> </section>
    <section class="post_form"> <%= render 'shared/post_form' %> </section> 
</div>

app/views/posts/show.html.erb
<%# 俺作った %>
<div class= "posts">
  <%= link_to gravatar_for(@post.user, size: 30), @post.user %>
  <span class="user">
    <%= @post.user.name %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(@post.created_at) %> ago.
  </span>
</div>
<div class="show-content">
  <%= render 'post_edit', post: @post %>

  <h1> <%= @post.title %> </h1> 
  <%= @post.content %>
</div>

<%# いいね機能 %>
<span id="favorite_icon_<%= @post.id %>">
  <% unless current_user?(@user) %>
    <% if @post.favorited?(current_user) %>
      <%= render 'favorites/favorited_state', post: @post %>
    <% else %>
      <%= render 'favorites/unfavorited_state', post: @post %>
    <% end %>
  <% end %>
</span>
  <span id="favorite_count" class="middle-size"><%= @post.favorites.count %></span>
<div class="link_to margin-top">
  <%= link_to "いいねしたユーザー", post_favorites_path(@post) %>
</div>

<ol id="favorite_users">
  <%= render partial: 'favorites/favorite_user', favorite_users: @favorite_users %>
</ol>

<%# コメント機能 %>
<p class="margin-top">コメントする</p>
  <%= render 'comments/comment_form' %>
<p class="margin-top">コメント一覧</p>
<% @comments.each do |comment| %>
  <div class="comments">
    <%= render 'shared/user_small_info', c: comment %>
    <div class="comment_content"> <%= comment.comment_content %> </div>
    <%= render 'comments/comment_edit', post: @post, c: comment %>
  </div>
<% end %>

<div>
  <%#= link_to :root do %>
    <%# <button class="btn margin-top">back</button> %>
  <%# end %>
</div>